name: CI

on: [ push ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - go-version: '1.23.x'
            staticcheck-version: v0.5.1
          - go-version: '1.24.x'
            staticcheck-version: v0.5.1
          - go-version: '1.25.x'
            staticcheck-version: v0.6.1

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.6

      - name: Test
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@${{ matrix.staticcheck-version }}
          go fmt ./...
          go vet ./...
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...
          $(go env GOPATH)/bin/staticcheck ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          verbose: true
