# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Codecov
on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  cover:
    runs-on: ubuntu-latest
    env:
      GOMODCACHE: ${{ github.workspace }}/.cache/go-mod
      GOCACHE: ${{ github.workspace }}/.cache/go-build

    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 1

      - name: Setup go 1.25.x
        id: setup-go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: 1.25.x

      - name: Restore Go module and build cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ${{ env.GOMODCACHE }}
            ${{ env.GOCACHE }}
          key: go-${{ steps.setup-go.outputs.go-version }}-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ steps.setup-go.outputs.go-version }}-${{ runner.os }}-

      - name: Run coverage
        run: go test -coverprofile=coverage.txt -covermode=atomic -v -count=1 ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          verbose: true
